---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types: ["major", "minor", "patch"]
      development-dependencies:
        dependency-type: "development"
        update-types: ["major", "minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    groups:
      all-dependencies:
        update-types: ["major", "minor", "patch"]

  - package-ecosystem: "docker"
    directories:
      - "/docker"
      - "/docker/images/*"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: python
        versions: [">=3.12"]
