---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: python
        versions: [">=3.12"]

