services:
  shell:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        userid: ${USE_UID:-10001}
        groupid: ${USE_GID:-10001}
    image: local/obs-common-shell
    env_file:
      - docker/config/local_dev.env
    links:
      - fakesentry
      - gcs-emulator
      - pubsub
    volumes:
      - .:/app

  devcontainer:
    build:
      dockerfile: .devcontainer/Dockerfile
      args:
        userid: ${USE_UID:-10001}
        groupid: ${USE_GID:-10001}
    image: local/obs-common-devcontainer
    entrypoint: ["sleep", "inf"]
    env_file:
      - docker/config/local_dev.env
    links:
      - fakesentry
      - gcs-emulator
      - pubsub
    volumes:
      - .:/app

  # https://github.com/willkg/kent
  fakesentry:
    build:
      context: docker/images/fakesentry
    image: local/obs-common-fakesentry
    ports:
      - "${EXPOSE_SENTRY_PORT:-8090}:8090"
    command: run --host 0.0.0.0 --port 8090
    stop_signal: SIGINT

  # https://github.com/fsouza/fake-gcs-server
  # Fake GCP GCS server for local development and testing
  gcs-emulator:
    build:
      context: docker/images/gcs-emulator
    image: local/obs-common-gcs-emulator
    command: -port 8001 -scheme http
    ports:
      - "${EXPOSE_GCS_EMULATOR_PORT:-8001}:8001"

  # https://cloud.google.com/sdk/docs/downloads-docker
  # official pubsub emulator
  pubsub:
    build:
      context: docker/images/pubsub-emulator
    image: local/obs-common-pubsub-emulator
    command:
      - gcloud
      - beta
      - emulators
      - pubsub
      - start
      - --host-port=0.0.0.0:5010
    ports:
      - "${EXPOSE_PUBSUB_EMULATOR_PORT:-5010}:5010"
    stop_signal: SIGINT
