name: Test, build, and release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync
      - name: Install just
        run: sudo apt-get update && sudo apt-get install -y just
      - name: Run lint check
        if: ${{ matrix.python-version == '3.11' }}
        run: just lint
      - name: Run tests
        run: |
          just test
          # stop services immediate and ignore errors
          just down -t0 || true

  build-and-release:
    permissions:
      contents: write
      id-token: write
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: test
    runs-on: ubuntu-latest
    concurrency:
      group: release
    steps:
      - uses: actions/checkout@v6
      - name: Fetch tags
        run: git fetch --tags origin
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.11
      - name: Install dependencies
        run: uv sync
      - name: Generate release tag
        run: echo RELEASE_TAG="$(uv run python -c 'import obs_common.release; print(obs_common.release.generate_tag())')" >> "$GITHUB_ENV"
      - name: Overrride wheel version
        run: |
          # Convert version number to PEP 440-conformant version that's treated correctly
          # by Dependabot, see https://mozilla-hub.atlassian.net/browse/CRINGE-24.
          VERSION="${RELEASE_TAG#v}"
          MAIN_VERSION="${VERSION%-*}"
          case "$VERSION" in
            *-*) SUBVERSION=".${VERSION##*-}";;
            *) SUBVERSION="";;
          esac
          uv version "$MAIN_VERSION$SUBVERSION"
      - name: Build python wheel
        run: uv build --wheel
      - name: Build docker images for publishing
        run: |
          just build fakesentry gcs-emulator
          GAR_REPO="us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cavendish-prod"
          FAKESENTRY_TAG="$GAR_REPO/fakesentry:${{ env.RELEASE_TAG }}"
          docker tag local/obs-common-fakesentry:latest "$FAKESENTRY_TAG"
          GCS_EMULATOR_TAG="$GAR_REPO/gcs-emulator:${{ env.RELEASE_TAG }}"
          docker tag local/obs-common-gcs-emulator:latest "$GCS_EMULATOR_TAG"
          echo "DOCKER_IMAGE_TAGS<<EOF
          $FAKESENTRY_TAG
          $GCS_EMULATOR_TAG
          EOF" >> "$GITHUB_ENV"
      - uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ vars.GCPV2_GITHUB_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: artifact-writer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
      - name: Push fakesentry and gcs-emulator Docker images to GAR
        uses: mozilla-it/deploy-actions/docker-push@v6.2.2
        with:
          image_tags: ${{ env.DOCKER_IMAGE_TAGS }}
          workload_identity_pool_project_number: ${{ vars.GCPV2_WORKLOAD_IDENTITY_POOL_PROJECT_NUMBER }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Publish python package
        run: |
          uv tool install keyring --with keyrings.google-artifactregistry-auth
          uv publish --index=cavendish --keyring-provider=subprocess --username=oauth2accesstoken
      - name: Publish release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "$RELEASE_TAG" --repo="$GITHUB_REPOSITORY" --generate-notes dist/*.whl
