# Define this image outside of docker-compose.yml so that it gets dependabot updates
FROM gcr.io/google.com/cloudsdktool/google-cloud-cli:561.0.0-emulators@sha256:6c778b499a1fc199c3b84db5c19e7db0d41ebe8166cd1243c19a38b4b826b427
# also available as google/cloud-sdk:<version>-emulators
