# Define this image outside of docker-compose.yml so that it gets dependabot updates
FROM gcr.io/google.com/cloudsdktool/google-cloud-cli:581.0.0-emulators@sha256:25300472f1fa63b4df0e0c3a5dd67bdc6774b39f6dd440605e520a6d04ae0f26
# also available as google/cloud-sdk:<version>-emulators
